### ISSUE TITLE
Hi, Is there tutorial about this plugin?

### ISSUE THREAD

**Issue by zhw2590582** [turtlepod/fx-updater#4]
I've been looking for like this plugin,thanks

**Comment by turtlepod** [comment]
sorry, currently still experimental.
I'll let you know when it's ready.

**Comment by zhw2590582** [comment]
Thank you, expecting you complete this plugin.

**Comment by Ataurr** [comment]
Is it ready now ?

**Comment by turtlepod** [comment]
hi all, sorry I was busy with client project,
but I'll be publish this plugin this weekend and will write short tutorial in how to use it.

**Comment by turtlepod** [comment]
sorry, been very busy.

here's the plugin page:
https://genbumedia.com/plugins/fx-updater/
docs page link is in the sidebar.

sorry, for limited explanation/docs.

**Comment by turtlepod** [comment]
Hi All,

I just updated f(x) Updater plugin with more information in how to set it
up:
https://genbumedia.com/docs/fx-updater-docs/

I hope the explanation in the documentation is clear enough.
But let me know if you need more information.

best regards,
David.
