### ISSUE TITLE
How to introduce update files in the theme?

### ISSUE THREAD

**Issue by zhw2590582** [turtlepod/fx-updater#6]
Hello, it's me again. I see this plugin documentation.And I try use it on the theme.
I copy the file(includes/updater.php) and paste to the theme.
In my functions.php add code like it:
require_once dirname( **FILE** ) .'updater.php';
But "HTTP ERROR 500" in chrome, Did I do something wrong?
Thank you very much！

**Comment by turtlepod** [comment]
Hi Harvey,

To be honest, This is a developer tool,
If you don't know how to include a file in PHP (which is very basic). I actually don't recommend to use this tool. And I don't really have time to teach you.
So, I'm really sorry. I'm closing this issue.

However, here's an example code to include in parent theme:

```
require_once get_template_directory() . '/inc/updater.php';
```

And for further example. Here's a theme where I use the updater. Check the config args where I setup the server, etc..
https://github.com/turtlepod/nokonoko/blob/master/includes/updater.php

Have fun learning PHP :)
I wish you luck,
