### ISSUE TITLE
Code of connection

### ISSUE THREAD

**Issue by iLenTheme** [turtlepod/fx-updater#7]
Hello, interesting panel admin updates plugins and themes, but there is no documentation of the code that has to have the plugin or theme to connect with this update manager? 

-In the 'server' field that gets there?
-In the field 'id' I do not understand why that link goes
```
/* Updater Config */
$this->config = array(
	'server'  => 'http://genbumedia.com/',
	'type'    => 'plugin',
	'id'      => 'fx-updater/fx-updater.php',
	'api'     => '1.0.0',
	'post'    => array(),
);
```

Please, I would like you to expand the documentation

**Comment by turtlepod** [comment]
you can read here:
https://genbumedia.com/docs/fx-updater-docs/
