### ISSUE TITLE
File path security.

### ISSUE THREAD

**Issue by WPDevHQ** [turtlepod/fx-updater#9]
I'd love to use this for my projects but I'm a bit concerned about the file path's security.

How secure is it and what how to further strengthen that security to avoid unauthorised downloads?

**Comment by turtlepod** [comment]
file path security?
what security do you refer to?

**Comment by WPDevHQ** [comment]
Upon uploading a file the location i.e. the upload folder - files in this folder can be publically accessible.

Would be nice to have an option to define the upload location

**Comment by turtlepod** [comment]
yes it is publicly available.
This plugin have no restriction feature at all.

Sorry, no plan in near future to add this feature to this plugin.
You can extend it, if needed.
All API data are filterable:
https://github.com/turtlepod/fx-updater/blob/master/includes/api/api.php

*Maybe Steps:*

1) create your own uploader in edit screen
2) filter the download url with your protected download URL.

**Comment by WPDevHQ** [comment]
Didn't notice the API.

Going to improvise with it and spin a remote server, thanks :)

**Comment by turtlepod** [comment]
there's also other alternative like EDD, if you need restriction feature (note: i never use it)
https://easydigitaldownloads.com/downloads/software-licensing/

**Comment by WPDevHQ** [comment]
I'm good with - a little workaround and all is secure for my needs :) 

Closing as a none issue, thanks for the input 👍
